const terminologieData = {
  lagebezeichnungen: [
    { term: 'cranial', bedeutung: 'kopfwärts, zum Kopf hin (oben)' },
    { term: 'caudal', bedeutung: 'schwanzwärts, vom Kopf weg (unten)' },
    { term: 'anterior / ventral', bedeutung: 'vorne, zur Bauchseite' },
    { term: 'posterior / dorsal', bedeutung: 'hinten, zur Rückenseite' },
    { term: 'medial', bedeutung: 'zur Körpermittellinie hin' },
    { term: 'lateral', bedeutung: 'von der Körpermittellinie weg, seitwärts' },
    { term: 'proximal', bedeutung: 'rumpfnah (bei Extremitäten: näher am Körperstamm)' },
    { term: 'distal', bedeutung: 'rumpffern (bei Extremitäten: weiter vom Körperstamm entfernt)' },
    { term: 'superior', bedeutung: 'oberhalb liegend, oben' },
    { term: 'inferior', bedeutung: 'unterhalb liegend, unten' },
    { term: 'superfizial', bedeutung: 'oberflächlich, hautnah' },
    { term: 'profund / tief', bedeutung: 'tief gelegen, von der Oberfläche entfernt' },
    { term: 'ipsilateral', bedeutung: 'auf der gleichen Körperseite' },
    { term: 'kontralateral', bedeutung: 'auf der gegenüberliegenden Körperseite' },
    { term: 'bilateral', bedeutung: 'beidseitig, auf beiden Seiten' },
    { term: 'sagittal', bedeutung: 'Pfeilrichtung (vorne–hinten); teilt Körper in links/rechts' },
    { term: 'frontal / koronal', bedeutung: 'Stirnebene; teilt Körper in vorne/hinten' },
    { term: 'transversal / horizontal', bedeutung: 'Querebene; teilt Körper in oben/unten' },
    { term: 'zentral', bedeutung: 'zur Mitte des Nervensystems hin (Gehirn/Rückenmark)' },
    { term: 'peripher', bedeutung: 'vom Zentrum des Nervensystems weg' },
  ],
  bewegungsrichtungen: [
    { bewegung: 'Flexion', erklaerung: 'Beugung – Verringerung des Gelenkwinkels' },
    { bewegung: 'Extension', erklaerung: 'Streckung – Vergrößerung des Gelenkwinkels' },
    { bewegung: 'Abduktion', erklaerung: 'Wegführen von der Körpermittellinie' },
    { bewegung: 'Adduktion', erklaerung: 'Heranführen zur Körpermittellinie' },
    { bewegung: 'Innenrotation', erklaerung: 'Drehung nach medial (zur Körpermitte hin)' },
    { bewegung: 'Außenrotation', erklaerung: 'Drehung nach lateral (von der Körpermitte weg)' },
    { bewegung: 'Pronation', erklaerung: 'Einwärtsdrehung des Unterarms – Handfläche zeigt nach unten/hinten' },
    { bewegung: 'Supination', erklaerung: 'Auswärtsdrehung des Unterarms – Handfläche zeigt nach oben/vorne' },
    { bewegung: 'Dorsalextension', erklaerung: 'Heben des Fußrückens Richtung Schienbein (Ferse am Boden)' },
    { bewegung: 'Plantarflexion', erklaerung: 'Senken des Fußes (Zehenspitzenstand, Gaspedaltreten)' },
    { bewegung: 'Inversion', erklaerung: 'Fußsohle dreht nach medial (innen) – Supinationskomponente' },
    { bewegung: 'Eversion', erklaerung: 'Fußsohle dreht nach lateral (außen) – Pronationskomponente' },
    { bewegung: 'Zirkumduktion', erklaerung: 'Kreisförmige Bewegung als Kombination aller Bewegungsachsen' },
    { bewegung: 'Elevation', erklaerung: 'Anheben (z.B. Schulterblatt nach oben)' },
    { bewegung: 'Depression', erklaerung: 'Absenken (z.B. Schulterblatt nach unten)' },
    { bewegung: 'Retraktion', erklaerung: 'Rückwärtsbewegung (Schulterblatt Richtung Wirbelsäule)' },
    { bewegung: 'Protraktion', erklaerung: 'Vorwärtsbewegung (Schulterblatt weg von Wirbelsäule)' },
  ],
  glossar: [
    { lat: 'Os / Ossa', de: 'Knochen / Knochen (Pl.)' },
    { lat: 'Articulatio', de: 'Gelenk' },
    { lat: 'Musculus / Musculi', de: 'Muskel / Muskeln' },
    { lat: 'Nervus / Nervi', de: 'Nerv / Nerven' },
    { lat: 'Arteria / Arteriae', de: 'Arterie / Arterien' },
    { lat: 'Vena / Venae', de: 'Vene / Venen' },
    { lat: 'Ligamentum / Ligamenta', de: 'Band / Bänder' },
    { lat: 'Tendo / Tendines', de: 'Sehne / Sehnen' },
    { lat: 'Caput', de: 'Kopf' },
    { lat: 'Collum', de: 'Hals' },
    { lat: 'Corpus', de: 'Körper / Schaft' },
    { lat: 'Processus', de: 'Fortsatz' },
    { lat: 'Foramen', de: 'Loch / Öffnung im Knochen' },
    { lat: 'Fossa', de: 'Grube / Vertiefung' },
    { lat: 'Sulcus', de: 'Furche / Rinne' },
    { lat: 'Tuberositas', de: 'Rauigkeit / großer Höcker' },
    { lat: 'Tuberculum', de: 'Kleiner Höcker' },
    { lat: 'Epicondylus', de: 'Knochenvorsprung über dem Kondylus' },
    { lat: 'Condylus', de: 'Gelenkknorren' },
    { lat: 'Spina', de: 'Dorn / Stachel (z.B. Spina iliaca)' },
    { lat: 'Crista', de: 'Kamm / Leiste (z.B. Crista iliaca)' },
    { lat: 'Facies', de: 'Fläche / Seite' },
    { lat: 'Margo', de: 'Rand' },
    { lat: 'Plexus', de: 'Geflecht (z.B. Plexus brachialis)' },
    { lat: 'Ganglion', de: 'Nervenknoten' },
    { lat: 'Periosteum', de: 'Knochenhaut' },
    { lat: 'Cartilago', de: 'Knorpel' },
    { lat: 'Fascia', de: 'Bindegewebshülle / Faszie' },
    { lat: 'Bursa', de: 'Schleimbeutel' },
    { lat: 'Capsula articularis', de: 'Gelenkkapsel' },
  ],
  karteikarten: [
    { q: 'Was bedeutet "cranial" und "caudal"?', a: 'Cranial = kopfwärts (oben)\nCaudal = schwanzwärts (unten)\nBeide beschreiben die Lage entlang der Körperlängsachse.' },
    { q: 'Was ist der Unterschied zwischen anterior/ventral und posterior/dorsal?', a: 'Anterior / ventral = vorne, zur Bauchseite\nPosterior / dorsal = hinten, zur Rückenseite\nBeim aufrechten Menschen: ventral = anterior.' },
    { q: 'Was bedeutet proximal und distal?', a: 'Proximal = rumpfnah (nahe am Körperstamm)\nDistal = rumpffern (weit vom Körperstamm)\nBeispiel: Das Knie ist proximal des Fußes, aber distal des Hüftgelenks.' },
    { q: 'Was ist der Unterschied zwischen Flexion und Extension?', a: 'Flexion = Beugung → Verkleinerung des Gelenkwinkels\nExtension = Streckung → Vergrößerung des Gelenkwinkels\nBeispiel: Bizepskontraktion → Ellbogenflexion.' },
    { q: 'Was bedeuten Abduktion und Adduktion?', a: 'Abduktion = Wegführen von der Körpermittellinie\nAdduktion = Heranführen zur Körpermittellinie\nMerke: Ab = weg (wie "abdanken"), Ad = heran (wie "addieren").' },
    { q: 'Was ist der Unterschied zwischen Pronation und Supination?', a: 'Pronation = Einwärtsdrehung des Unterarms (Handfläche nach unten/hinten)\nSupination = Auswärtsdrehung (Handfläche nach oben/vorne)\nMerke: "Suppe tragen" = Supination (Handfläche nach oben).' },
    { q: 'Was bedeuten Inversion und Eversion am Fuß?', a: 'Inversion = Fußsohle dreht nach medial (innen)\nEversion = Fußsohle dreht nach lateral (außen)\nBeim "Umknicken" nach innen: Supination = Inversion + Plantarflexion.' },
    { q: 'Was ist der Unterschied zwischen ipsilateral und kontralateral?', a: 'Ipsilateral = auf der gleichen Seite wie die Läsion/Referenz\nKontralateral = auf der gegenüberliegenden Seite\nKlinisch: Brown-Séquard-Syndrom → ipsilat. Motorik, kontralat. Schmerz.' },
    { q: 'Welche 3 Körperebenen gibt es und was beschreiben sie?', a: '1. Sagittalebene: teilt in links/rechts (Pfeilrichtung)\n2. Frontal-/Koronalebene: teilt in vorne/hinten\n3. Transversal-/Horizontalebene: teilt in oben/unten\nCT-/MRT-Schnitte folgen diesen Ebenen.' },
    { q: 'Was bedeutet "superfizial" vs. "profund/tief"?', a: 'Superfizial = oberflächlich, hautnah\nProfund / tief = von der Oberfläche entfernt, im Körperinneren\nBeispiel: V. saphena magna ist superfizial; A. femoralis liegt tief.' },
  ],
  quiz: [
    { q: 'Was bedeutet "distal" bei einer Extremität?', opts: ['Rumpfnah', 'Rumpffern', 'Oberflächlich', 'Hinten gelegen'], correct: 1, exp: 'Distal = rumpffern. Beispiel: Die Hand liegt distal des Ellbogens. Proximal = rumpfnah.' },
    { q: 'Ein Patient hat eine linksseitige Läsion. Der ipsilaterale Arm ist...', opts: ['Der rechte Arm', 'Beide Arme', 'Der linke Arm', 'Keiner der Arme'], correct: 2, exp: 'Ipsilateral = gleiche Seite. Bei linksseitiger Läsion ist der ipsilaterale Arm der linke Arm.' },
    { q: 'Welche Bewegung bringt die Handfläche nach oben (Suppenteller halten)?', opts: ['Pronation', 'Supination', 'Flexion', 'Extension'], correct: 1, exp: 'Supination = Auswärtsdrehung des Unterarms → Handfläche nach oben. Merke: "Suppe tragen" = Supination.' },
    { q: 'Welche Ebene teilt den Körper in vordere und hintere Hälften?', opts: ['Sagittalebene', 'Transversalebene', 'Frontal-/Koronalebene', 'Medianebene'], correct: 2, exp: 'Die Frontal- (Koronal-)ebene teilt in anterior und posterior. Die Sagittalebene teilt in links/rechts.' },
    { q: 'Was bedeutet Abduktion der Schulter?', opts: ['Arm zur Körpermitte führen', 'Arm seitwärts vom Körper wegführen', 'Arm nach vorne führen', 'Arm nach innen rotieren'], correct: 1, exp: 'Abduktion = Wegführen von der Körpermittellinie. Bei der Schulter: Arm seitwärts heben. Ab = weg.' },
    { q: 'Dorsalextension des Fußes bedeutet...', opts: ['Fußsohle zeigt nach unten (Spitzfuß)', 'Fußrücken hebt sich Richtung Schienbein', 'Fuß dreht nach innen', 'Fuß dreht nach außen'], correct: 1, exp: 'Dorsalextension = Heben des Fußrückens Richtung Schienbein. Gegenteil: Plantarflexion (Zehenspitzenstand).' },
  ],
};
